######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 28 14:41:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bouncingrectangle.h mainwindow.h
SOURCES += bouncingrectangle.cpp main.cpp mainwindow.cpp
